openapi: '3.0.3'
info:
  title: Tenant Config Service
  version: '1.0'
servers:
  - url: https://localhost:9999/api/v1
tags:
  - name: config
    description: Configuration entries for tenants
paths:
  '/config/{id}':
    $ref: './paths/config.yml'

components: 
  securitySchemes: 
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize 
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: 'Read access'
            write: 'Write access'
    # api_key: 
    #   type: apiKey
    #   in: header
    #   name: X-API-Key
