openapi: '3.0.3'
info:
  title: Tenant Config Service
  version: '1.0'
servers:
  - url: https://localhost:9999/api/v1
tags:
  - name: config
    description: Configuration entries for tenants
paths:
  '/config/{id}':
    get:
      tags:
        - config
      summary: Retrieve Tenant Specific Configuration
      description: |
        Retrieves Tenant Configuration for the corresponding identifier.
      operationId: RetrieveConfig
      security: 
        - oauth:
          - read
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          minimum: 7
          maximum: 10
          format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema: 
                $ref: '#/components/schemas/Configuration'
        '401':
          description: Not Authorized
        '403':
          description: Unauthorized
        '404':
          description: Not found
        '406':
          description: Not acceptable
        '429':
          description: Too many requests

    post:
      summary: Create Tenant Specific Configuration
      description: |
        Creates a new tenant config if the input tenant ID is not present.
      operationId: UpdateConfig
      security: 
        - oauth:
          - read
          - write
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          minimum: 7
          maximum: 10
          format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema: 
                $ref: '#/components/schemas/Configuration'
        '401':
          description: Not Authorized
        '403':
          description: Unauthorized
        '404':
          description: Not found
        '406':
          description: Not acceptable
        '429':
          description: Too many requests

    put:
      summary: Create/Update Tenant Specific Configuration
      description: |
        Partial update of configuration of existing tenant identifier is passed then the configuration is updated.
      operationId: CreateConfig
      security: 
        - oauth:
          - read
          - write
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          minimum: 7
          maximum: 10
          format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema: 
                $ref: '#/components/schemas/Configuration'
        '401':
          description: Not Authorized
        '403':
          description: Unauthorized
        '404':
          description: Not found
        '406':
          description: Not acceptable
        '429':
          description: Too many requests

components: 
  schemas:
    Configuration:
      type: object
      properties:
        tenant-name:
          description: Readable name of the tenant
          type: string

  securitySchemes: 
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize 
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: 'Read access'
            write: 'Write access'
    # api_key: 
    #   type: apiKey
    #   in: header
    #   name: X-API-Key
